exclude: '.git|.tox'
files: 'serde/|tests/|examples/|bench/bench.py'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args:
          - .
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.345
    hooks:
    - id: pyright
      additional_dependencies: ['pyyaml', 'msgpack', 'msgpack-types']
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.254
    hooks:
    - id: ruff
      args:
        - --fix
